/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xzzpig#1' at '17-6-14 下午5:45' with Gradle 2.14.1
 *
 * @author xzzpig#1, @date 17-6-14 下午5:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
